'use strict';

var _DocEstrutura = require('./controller/DocEstrutura');

var json = '\n{\n    "label": "ESTRUTURA DO DOCUMENTO",\n    "id": "root",\n    "seq": 0,\n    "tipo": "agregador",\n    "itens": [{\n        "label": "NOME",\n        "id": "texto1",\n        "chave": "texto1",\n        "seq": 1,\n        "obrigatorio": false,\n        "regex": "",\n        "tipo": "texto"\n    }, {\n        "label": "IDADE",\n        "id": "numero2",\n        "chave": "numero2",\n        "obrigatorio": false,\n        "regex": "",\n        "tipo": "numero"\n    }, {\n        "label": "ENDERE\xC7O",\n        "id": "agregador3",\n        "chave": "agregador3",\n        "seq": 3,\n        "tipo": "agregador",\n        "itens": [{\n            "label": "LOG",\n            "id": "texto4",\n            "chave": "texto4",\n            "seq": 4,\n            "obrigatorio": false,\n            "regex": "",\n            "tipo": "texto"\n        }, {\n            "label": "BAIRRO",\n            "id": "texto5",\n            "chave": "texto5",\n            "seq": 5,\n            "obrigatorio": false,\n            "regex": "",\n            "tipo": "texto"\n        }]\n    }, {\n        "label": "LISTAGEM",\n        "id": "listagem6",\n        "chave": "listagem6",\n        "seq": 6,\n        "tipo": "listagem",\n        "itens": [{\n            "label": "NOME",\n            "id": "texto7",\n            "chave": "texto7",\n            "seq": 7,\n            "obrigatorio": false,\n            "regex": "",\n            "tipo": "texto"\n        }, {\n            "label": "CPF",\n            "id": "texto8",\n            "chave": "texto8",\n            "seq": 8,\n            "obrigatorio": false,\n            "regex": "",\n            "tipo": "texto"\n        }, {\n            "label": "CONCURSADO",\n            "id": "lista10",\n            "chave": "lista10",\n            "obrigatorio": false,\n            "tipo": "lista",\n            "seq": 10,\n            "opcoes": ["Sim", "N\xE3o", "Sim", "N\xE3o"]\n        }, {\n            "label": "NOME DO GRUPO",\n            "id": "agregador11",\n            "chave": "agregador11",\n            "seq": 11,\n            "tipo": "agregador",\n            "itens": [{\n                "label": "CTPS",\n                "id": "texto12",\n                "chave": "texto12",\n                "seq": 12,\n                "obrigatorio": false,\n                "regex": "",\n                "tipo": "texto"\n            }, {\n                "label": "PIS",\n                "id": "texto13",\n                "chave": "texto13",\n                "seq": 13,\n                "obrigatorio": false,\n                "regex": "",\n                "tipo": "texto"\n            }]\n        }]\n    }]\n}\n';

(0, _DocEstrutura.currentInstance)().iniciaConstrucao(json, false);
$("#btn-parse").on('click', function () {
    (0, _DocEstrutura.currentInstance)().montaJson();
});
//# sourceMappingURL=boot.js.map